# Generated by Django 5.0.1 on 2024-01-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complainttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintType_name', models.CharField(max_length=100)),
            ],
        ),
    ]
