# Generated by Django 5.0.1 on 2024-02-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_complainttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_providertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providertype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
