# Generated by Django 5.0.1 on 2024-02-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_complainttype',
        ),
        migrations.DeleteModel(
            name='tbl_department',
        ),
        migrations.DeleteModel(
            name='tbl_designation',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_freelancertype',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.DeleteModel(
            name='tbl_providertype',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
