# Generated by Django 5.0.1 on 2024-02-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_complainttype',
        ),
        migrations.DeleteModel(
            name='tbl_department',
        ),
        migrations.DeleteModel(
            name='tbl_designation',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_freelancertype',
        ),
        migrations.DeleteModel(
            name='tbl_providertype',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
