# Generated by Django 5.0.3 on 2024-03-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0017_tbl_admin'),
        ('Guest', '0006_remove_tbl_freelancer_freelancer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('job_contact', models.CharField(max_length=50)),
                ('job_email', models.CharField(max_length=50)),
                ('job_details', models.CharField(max_length=500)),
                ('job_lastdate', models.CharField(max_length=500)),
                ('job_minqual', models.CharField(max_length=500)),
                ('job_salaryscale', models.CharField(max_length=500)),
                ('job_status', models.IntegerField(default='0')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_provider')),
            ],
        ),
    ]
