# Generated by Django 5.0.1 on 2024-02-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_name', models.CharField(max_length=50)),
                ('freelancer_email', models.CharField(max_length=50)),
                ('freelancer_contact', models.CharField(max_length=50)),
                ('freelancer_address', models.CharField(max_length=50)),
                ('freelancer_password', models.CharField(max_length=50)),
                ('freelancer_photo', models.CharField(max_length=50)),
                ('freelancer_proof', models.CharField(max_length=50)),
                ('freelancer_type', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_providerregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerregistration_name', models.CharField(max_length=50)),
                ('providerregistration_email', models.CharField(max_length=50)),
                ('providerregistration_contact', models.CharField(max_length=50)),
                ('providerregistration_address', models.CharField(max_length=50)),
                ('provider_photo', models.CharField(max_length=50)),
                ('provider_proof', models.CharField(max_length=50)),
                ('provider_password', models.CharField(max_length=50)),
                ('provider_vstatus', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('providertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_providertype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
