# Generated by Django 5.0.1 on 2024-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(null=True, upload_to='UserDoc/'),
        ),
    ]
