# Generated by Django 5.0.3 on 2024-03-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_freelancer_tbl_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_freelancer',
            name='freelancer_gender',
        ),
    ]
