# Generated by Django 5.0.3 on 2024-03-29 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_remove_tbl_freelancer_freelancer_gender'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_postdate', models.DateField(auto_now_add=True)),
                ('booking_fordate', models.CharField(max_length=500)),
                ('booking_message', models.CharField(max_length=500)),
                ('booking_status', models.IntegerField(default='0')),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_freelancer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
