# Generated by Django 5.0.3 on 2024-03-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_remove_tbl_freelancer_freelancer_gender'),
        ('User', '0002_tbl_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_postdate', models.DateField(auto_now_add=True)),
                ('application_resume', models.FileField(upload_to='Assets/UserResume/')),
                ('application_message', models.CharField(max_length=500)),
                ('application_status', models.IntegerField(default='0')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_freelancer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
